import Head from "next/head";
import Image from "next/image";
import { theme, styled } from "../stitches.config";
import styles from "../styles/Home.module.css";
import * as AspectRatio from "@radix-ui/react-aspect-ratio";
import PluralsightSection from "../profile_sections/PluralsightSection";
import GithubSection from "../profile_sections/GithubSection";
import CalendarSection from "../profile_sections/CalendarSection";
import LeetcodeSection from "../profile_sections/LeetcodeSection";
export const H1 = styled("h1", {});
export const H2 = styled("h2", {});
export const A = styled("a", {});
export const P = styled("p", {});
export const Button = styled("button", {});
export const Input = styled("input", {});
export const Div = styled("div", {});
export const Main = styled("main", {})
export const Aspect = styled(AspectRatio.Root, {})

export default function Home() {
  const A1 = styled("a",{
    margin: "1rem",
    padding: "1.5rem",
    textAlign: "left",
    color: "inherit",
    textDecoration: "none",
    border: "1px solid #eaeaea",
    borderRadius: "10px",
    transition: "color 0.15s ease, border-color 0.15s ease",
    maxWidth: "max-content"
  })
  const NoA = styled("div",{
    margin: "1rem",
    padding: "1.5rem",
    textAlign: "left",
    color: "inherit",
    textDecoration: "none",
    border: "1px solid #eaeaea",
    borderRadius: "10px",
    transition: "color 0.15s ease, border-color 0.15s ease",
    height: "max-content",
    width: "max-content"
  })
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Zakhary Oliver</title>
        <meta
          name="Zakhary Oliver's portfolio"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="https://lh3.googleusercontent.com/a-/AOh14Gi_P_FSiBCwqZgeBLmzPUzlTi98EvTEzWlN_Fdp=s288-p-rw-no"
        />
      </Head>

      <Main
          css={{
            border: "solid",
            minHeight: '1000vh',
            padding: "4rem 0",
            flex: "1",
            display: "flex",
            flexDirection: "column",
            justifyItems: "center",
            alignItems: "center"
        }}
      >
        <H1>
          Welcome to{" "}
          <a href="https://www.linkedin.com/in/zakhary-oliver-81141b211/">
            Zakhary Oliver's Portfolio
          </a>
        </H1>

        <P>
          Schedule a appointment with me <code>/calendar</code>
        </P>
          <Div
            css={{
              display: "grid",
              gridTemplateColumns: "1fr 1fr",
              alignItems: "center",
              justifyContent: "center",
              flexWrap: "wrap",
              border: "solid",
              maxWidth: "1500px"
          }}
          >
            
            <NoA >
                <H2>Calendar</H2>
              <P>Schedule an appointment here</P>
              <CalendarSection />
            </NoA>
            <A1 href="leetcode.com/Zakpak0">
              <H2>Problem Solving Skills</H2>
              <P>Leet Code</P>
              {/* <LeetcodeSection /> */}
                </A1>
            <A1 href="pluralsight.com/zakpak0">
              <H2>Technical Skills</H2>
              <P>Pluralsight</P>
              {/* <PluralsightSection /> */}
            </A1>
            <A1 href="github.com/zakpak0">
              <H2>Repositories</H2>
              <P>Github profile</P>
              {/* <GithubSection /> */}
            </A1>
          </Div>
    
      </Main>
    </div>
    </>
  );
}
