import Head from "next/head";
import Image from "next/image";
import { theme, styled } from "../stitches.config";
import styles from "../styles/Home.module.css";
import * as AspectRatio from "@radix-ui/react-aspect-ratio";
import PluralsightSection from "../profile_sections/Pluralsight/PluralsightSection.js";
import GithubSection from "../profile_sections/Github/GithubSection.js";
import CalendarSection from "../profile_sections/Calendar/CalendarSection.js";
import LeetcodeSection from "../profile_sections/Leetcode/LeetcodeSection.js";
export default function Home() {
  const H1 = styled('h1', {})
  const P = styled('p', {})
  const H2 = styled('h2', {})
  const A1 = styled("a",{
    margin: "1rem",
    padding: "1.5rem",
    textAlign: "left",
    color: "inherit",
    textDecoration: "none",
    border: "1px solid #eaeaea",
    borderRadius: "10px",
    transition: "color 0.15s ease, border-color 0.15s ease",
    maxWidth: "max-content"
  })
  const NoA = styled("div",{
    margin: "1rem",
    padding: "1.5rem",
    textAlign: "left",
    color: "inherit",
    textDecoration: "none",
    border: "1px solid #eaeaea",
    borderRadius: "10px",
    transition: "color 0.15s ease, border-color 0.15s ease",
    height: "max-content",
    width: "max-content"
  })
  const Main = styled("main", {
    border: "1px solid #eaeaea",
    borderRadius: "10px",
    transition: "color 0.15s ease, border-color 0.15s ease",
    minHeight: '1000vh',
    padding: "4rem 0",
    flex: "1",
    display: "flex",
    flexDirection: "column",
    justifyItems: "center",
    alignItems: "center"
  })
  const Div = styled("div", {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    maxWidth: "1500px"
 });
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Zakhary Oliver</title>
        <meta
          name="Zakhary Oliver's portfolio"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="https://lh3.googleusercontent.com/a-/AOh14Gi_P_FSiBCwqZgeBLmzPUzlTi98EvTEzWlN_Fdp=s288-p-rw-no"
        />
      </Head>

      <Main>
        <H1>
          Welcome to{" "}
          <a href="https://www.linkedin.com/in/zakhary-oliver-81141b211/">
            Zakhary Oliver's Portfolio
          </a>
        </H1>

        <P>
          Schedule a appointment with me <code>/calendar</code>
        </P>
          <Div>
            
            <NoA >
                <H2>Calendar</H2>
              <P>Schedule an appointment here</P>
              <CalendarSection />
            </NoA>
            <NoA >
              <H2>Problem Solving Skills</H2>
              <P>Leet Code</P>
              <LeetcodeSection />
                </NoA>
            <NoA>
              <H2>Technical Skills</H2>
              <P>Pluralsight</P>
              <PluralsightSection />
            </NoA>
            <A1 href="github.com/zakpak0">
              <H2>Repositories</H2>
              <P>Github profile</P>
              {/* <GithubSection /> */}
            </A1>
          </Div>
    
      </Main>
    </div>
    </>
  );
}
