import Head from "next/head";
import Image from "next/image";
import { theme, styled } from "../stitches.config";
import styles from "../styles/Home.module.css";

export default function Home() {
  const H1 = styled("h1", {});
  const H2 = styled("h2", {});
  const A = styled("a", {});
  const P = styled("p", {});
  const Button = styled("button", {});
  const Input = styled("input", {});
  const Div = styled("div", {});
  return (
    <div className={styles.container}>
      <Head>
        <title>Zakhary Oliver</title>
        <meta
          name="Zakhary Oliver's portfolio"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="https://lh3.googleusercontent.com/a-/AOh14Gi_P_FSiBCwqZgeBLmzPUzlTi98EvTEzWlN_Fdp=s288-p-rw-no"
        />
      </Head>

      <main>
        <H1>
          Welcome to{" "}
          <a href="https://www.linkedin.com/in/zakhary-oliver-81141b211/">
            Zakhary Oliver's Portfolio
          </a>
        </H1>

        <P>
          Schedule a appointment with me <code>/calendar</code>
        </P>

        <Div>
          <A href="calanderPage">
            <H2>Calendar</H2>
            <P>Schedule an appointment here</P>
          </A>

          <A href="leetcode.com/Zakpak0">
            <H2>Algorithmn</H2>
            <P>Leet Code</P>
          </A>

          <A href="pluralsight.com/zakpak0">
            <H2>Technical Skills</H2>
            <P>Pluralsight</P>
          </A>

          <A href="github.com/zakpak0">
            <H2>Repositories</H2>
            <P>Github profile</P>
          </A>
        </Div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
